# Generated by Django 5.1 on 2024-08-25 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_ticket_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='ticket',
        ),
        migrations.AddField(
            model_name='review',
            name='icket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.ticket'),
        ),
    ]
